main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.main, name="main"),
    path("sell/", views.sell, name="sell"),
    path("products/", views.all_products, name="all_products"),
    path("products/<str:category>", views.products_category, name="products_category"),
    path("products/<str:name>/", views.product_page, name="product_page"),
    path("search_product/", views.search_product, name="search_product"),
    path("profil", views.account, name="account"),
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("login_user/", views.login_user, name="login"),
    path("", views.logout_user, name="logout"),  # login_user/????
    path("register_user/", views.register_user, name="register"),
]

warzywoonlinepl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("users/", include("users.urls")),
    path("users/", include("django.contrib.auth.urls")),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=20)
    category = models.ManyToManyField(Category)
    # seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.name


class Opinion(models.Model):
    description = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    stars = models.IntegerField(
        validators=[MaxValueValidator(10), MinValueValidator(0)]
    )


class ProductToSell(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField(
        validators=[MaxValueValidator(99999), MinValueValidator(1)]
    )
    quantity = models.IntegerField(
        validators=[MaxValueValidator(999), MinValueValidator(1)]
    )
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_products = models.ManyToManyField(
        ProductToSell, blank=True
    )  # to tak działa XD?


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


# null=True blank=True????

users/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import ProductToSell


class ProductForm(ModelForm):
    class Meta:
        model = ProductToSell
        fields = ("product", "price", "quantity")

main/views.py
from django.shortcuts import render
from main.forms import ProductForm
from main.models import Product, Profile, ProductToSell, Category
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def main(request):
    return render(request, "main/index.html", {})


# @login_required(login_ur)
def sell(request):
    form = ProductForm
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            user_object = User.objects.get(username=request.user.username)
            user_profile = Profile.objects.get(user=user_object)
            item.seller = user_profile.user
            item.save()
            user_profile.user_products.add(item)

            print(item)
        else:
            print("???")
    return render(request, "main/seller_page.html", {"form": form})


def all_products(request):
    categories = Category.objects.all()
    products = Product.objects.all()

    return render(request, "main/all_products.html", {"products": products, "categories": categories})


def products_category(request, category):
    categories = Category.objects.all()
    products = Product.objects.filter(category__name=category)

    return render(request, "main/all_products.html", {"products": products, "categories": categories})


def product_page(request, name):

    products_to_sell = ProductToSell.objects.filter(product__name=name)
    
    try:
        name = products_to_sell[0].product.name
    except:
        name = "Brak ofert wybranego produktu"
    return render(
        request,
        "main/product_page.html",
        {
            "products_to_sell": products_to_sell,
            "name": name,
        },
    )


def search_product(request):
    if request.method == "POST":
        searched = request.POST.get("searched")
        products = Product.objects.filter(name__contains=searched)
        return render(
            request,
            "main/search_product.html",
            {
                "searched": searched,
                "products": products,
            },
        )
    else:
        return render(request, "main/search_product.html", {})


@login_required()
def account(request):
    user_object = User.objects.get(username=request.user.username)
    user_profile = Profile.objects.get(user=user_object)
    print(user_profile.user_products.all())
    return render(
        request,
        "main/account.html",
        {
            "user": user_object,
            "profile": user_profile,
            "products": user_profile.user_products.all(),
        },
    )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm


def login_user(request):
    print("login \n l")

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("main:main")
        else:
            messages.success(request, ("There Was An Error Logging In, Try Again..."))
            return redirect("users:login")

    else:
        return render(request, "users/authenticate/login.html", {})


def logout_user(request):
    print("HALO HALO \n HALO HALO HALO")
    logout(request)
    messages.success(request, ("Wylogowano poprawnie!"))
    return redirect("main:main")


def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("Zarejestrowano poprawnie!"))
            return redirect("main:main")
    else:
        form = UserCreationForm()

    return render(
        request,
        "users/authenticate/register_user.html",
        {
            "form": form,
        },
    )

main/templates/main/account.html
{% extends "main/base.html" %}

{% block content %}
<h1>{{user}}</h1>
{% for product in products %}
<p>{{product.product.name}}: quantity-{{product.quantity}}price:{{product.price}}$</p>

{%endfor%}
{% endblock %}
hehexd

main/templates/main/all_products.html
{% extends "main/base.html" %}

{% block content %}

{% for product in products %}

<a href="{% url 'main:product_page' product.name %}" class="btn btn-primary">
    {{product.name}}
</a>

{% endfor %}

{% for category in categories %}
<a href="{% url 'main:products_category' category %}" class="btn btn-primary">
    {{category}}
</a>
{% endfor %}

{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="pl">

<head>
    <meta chatset="utf-8" />
    <title>WARZYWONLINE</title>
    <meta http-equiv="X-Ua-Compatible" content="IE=edge,chrome=1">
    {% block head %}

    {% endblock %}
    <link rel="stylesheet" href="{%static 'main\style.css'%}?{% now 'U' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cabin+Sketch:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

</head>


<body>
    <header class="main_header">

        <a class="header_logo" href="{% url 'main:main' %}">
            <img class="header_logo_img" src="{% static 'main/img/carrot.png' %}">
            <h1>warzywOnline</h1>
        </a>

        <!-- pasek wyszukiwania -->
        <nav class="header_nav">
            <ol class="main_list">
                <li><a href="{% url 'main:all_products' %}">Produkty</a>
                </li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'users:logout' %}">Wyloguj</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}">Zaloguj
                        <ul>
                            <li><a href="{% url 'users:register' %}">Zarejestruj</a></li>
                        </ul>
                    </a></li>
                {% endif %}
                <!-- po zalogowaniu zmienia się w "Konto" -->

                <li><a href="{% url 'main:sell' %}">Sprzedaj</a>
                </li>
                <li><a href="{% url 'main:account' %}"> Profil</a></li>
                <form method="POST" action="{% url 'main:search_product' %}">
                    {% csrf_token %}

                    <input placeholder="Szukaj" name="searched">
                    <button class="submit"><span class="material-symbols-outlined">
                            search
                        </span> AAAA</button>
                    <!-- problems with styling button above -->
                    <!-- try do add some "A" and find out -->

                </form>
                </li>

            </ol>
        </nav>
        <div style="clear: both"></div>
    </header>


    <main class="main_content">
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock %}

        <footer>
            <div class="footer">
                <div class="inner_footer">
                    <div class="logo_container">
                        <img src="{% static 'main/img/carrot.png' %}">
                    </div>
                    <div class="footer_third">
                        <h1>Potrzebujesz Pomocy?</h1>
                        <a href="#">Zasady &amp Warunki</a>
                        <a href="#">Polityka Prywatności</a>
                    </div>
                    <div class="footer_third">
                        <h1>O nas</h1>
                        <a href="#">Nasze Cv</a>
                        <a href="#">Lorem Ipsum</a>
                    </div>
                    <div class="footer_third">
                        <h1>Zostaw Followa</h1>
                        <li><a href="https://github.com/podhay123"><i class="fa fa-github"></i></a></li>
                        <li><a href="https://github.com/raksOtoOskar"><i class="fa fa-github"></i></a></li>
                        <span>
                            Warzywonline<br>
                            Jakub Podhajski & Oskar Fryc<br>
                            Słoniowa 17/4<br>
                            35-112, Rezszów<br>
                            Wszelkie prawa zastrzeżone ©<br>
                        </span>
                    </div>
                </div>
            </div>
        </footer>
</body>

</html>

main/templates/main/index.html
{% extends "main/base.html" %}

{% block head %}
<meta name="descritpion" content="giełda owoców i warzyw online" />
<meta name="keywords" content="warzywa, owoce, jarmark, rynek">
<meta name="author" content="Oskar Fryc & Jakub Podhajski">
{% endblock %}

{% block content %}


{% endblock %}

main/templates/main/product_page.html
{% extends "main/base.html" %}

{% block content %}
<style>
    table,
    th,
    td {
        border: 1px solid black;
        padding: 5px;
    }
</style>
<br>
<center>
    <h1 style="font-size: 50px;">{{name}}</h1>
    {% if products_to_sell %}

    <table style="font-size: 25px;" width="50%">
        <tr>
            <th>Sprzedawca</th>
            <th>Ocena</th>
            <th>Max.Ilosc</th>
            <th>Cena</th>
            <th>KUP</th>
        </tr>
        {% endif %}
        {% for product in products_to_sell %}
        <tr>
            <th>{{ product.seller}}</th>
            <th></th>
            <th>{{ product.quantity}}</th>
            <th>{{ product.price}}</th>
            <th>KUP</th>
        </tr>
        {% endfor %}

    </table>
</center>
{% endblock %}

main/templates/main/search_product.html
{% extends "main/base.html" %}

{% block content %}
{% if searched %}
<h1>Wyszukales: {{ searched }}</h1>
<br>
{% for product in products %}
<a href="{% url 'main:product_page' product.name %}" class="btn btn-primary">
    {{product.name}}
</a>
{% endfor %}
{% else %}
<h1>Nie wyszukales :C</h1>
{% endif %}
{% endblock %}

main/templates/main/seller_page.html
{% extends 'main/base.html' %}

{% block content %}
{% if user.is_authenticated %}

<h1>Co chcesz sprzedać?</h1>
<br>
<form action="" method="POST">
    {% csrf_token %}

    <!-- name
    <input type="text" name="name">
    password
    <input type="password" name="password"> -->
    {{form.as_p}}
    <input type="submit" value="Submit" class="btn btn-secondary">

</form>
{% else %}
<h1>Najpierw musisz się zalogować</h1>
<a href="{% url 'users:login' %}">Zaloguj</a>
<a href="{% url 'users:register' %}">Nie masz konta? Zarejestruj się tutaj!</a>
{%endif%}
{% endblock %}